-- a. DISTINCT
SELECT DISTINCT DEPARTMENT FROM Worker;

-- b. WHERE (AND, OR, NOT, IN, BETWEEN, LIKE …)
SELECT * FROM Worker WHERE SALARY BETWEEN 100000 AND 500000;
SELECT * FROM Worker WHERE FIRST_NAME = 'Vipul' OR FIRST_NAME = 'Satish' ;
SELECT * FROM Worker WHERE FIRST_NAME IN ('Vipul','Satish');
SELECT * FROM Worker WHERE FIRST_NAME NOT IN ('Vipul','Satish');
SELECT * FROM Worker WHERE DEPARTMENT LIKE 'Admin%';

-- c. ORDER BY
SELECT * FROM Worker ORDER BY FIRST_NAME ASC;
SELECT * FROM Worker ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

-- d. LIMIT
SELECT DEPARTMENT FROM Worker LIMIT 5;
        
-- e. JOINS (INNER, LEFT, RIGHT, FULL)
SELECT DISTINCT W.FIRST_NAME, T.WORKER_TITLE
FROM Worker W
INNER JOIN Title T
on W.WORKER_ID = T.WORKER_REF_ID
AND T.WORKER_TITLE IN ('Manager');

SELECT DISTINCT W.FIRST_NAME, T.WORKER_TITLE
FROM Worker W
LEFT JOIN Title T
ON W.WORKER_ID = T.WORKER_REF_ID
AND T.WORKER_TITLE IN ('Manager');

SELECT DISTINCT W.FIRST_NAME, T.WORKER_TITLE
FROM Worker W
RIGHT JOIN Title T
ON W.WORKER_ID = T.WORKER_REF_ID
AND T.WORKER_TITLE IN ('Manager');

-- f. UNION, UNION ALL
SELECT * FROM Worker WHERE WORKER_ID <=5
UNION
SELECT * FROM (SELECT * FROM Worker W ORDER BY W.WORKER_ID DESC) AS W1 WHERE W1.WORKER_ID <=5;

SELECT FIRST_NAME, DEPARTMENT FROM Worker W WHERE W.DEPARTMENT='HR'
UNION ALL
SELECT FIRST_NAME, DEPARTMENT FROM Worker W1 WHERE W1.DEPARTMENT='HR';

-- g. AGGREGATE FUNCTIONS (COUNT, MIN, MAX, SUM, AVG)
SELECT COUNT(*) FROM Worker WHERE DEPARTMENT = 'Admin';
SELECT DEPARTMENT, SUM(Salary) FROM Worker GROUP BY DEPARTMENT;
SELECT DEPARTMENT, AVG(Salary) FROM Worker GROUP BY DEPARTMENT;
SELECT FIRST_NAME, SALARY FROM Worker WHERE SALARY=(SELECT MAX(SALARY) FROM Worker);
SELECT FIRST_NAME, SALARY FROM Worker WHERE SALARY=(SELECT MIN(SALARY) FROM Worker);

-- h. GROUP BY
SELECT DEPARTMENT, COUNT(DEPARTMENT) AS 'Number of Workers' FROM Worker GROUP BY DEPARTMENT;

-- i. HAVING
SELECT WORKER_TITLE, AFFECTED_FROM, COUNT(*)
FROM Title
GROUP BY WORKER_TITLE, AFFECTED_FROM
HAVING COUNT(*) > 1;

-- j. Subqueries.
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS Worker_Name, Salary
FROM Worker
WHERE WORKER_ID IN
(SELECT WORKER_ID FROM Worker
WHERE Salary BETWEEN 50000 AND 100000);





